import React from 'react'
import './page.module.sass'
export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="es">
            <body className={'body'}>{children}</body>
        </html>
    )
}
